### ISSUE TITLE
The "Custom" option is set in "about:preferences#privacy" page after enrolling in the treatmentDomain branch

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/fingerprinting-blocking-methods-study-addon#10]
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Affected Versions]:
- Firefox 69.0 Unbranded build
- Firefox 70.0.1 Unbranded build
- Firefox 71 Unbranded build

[Prerequisites]:
- Have a Firefox 69, 70 or 71 Unbranded build. 
- Have access to the stage delivery console.
- Have an active branched-addon recipe for the Fingerprinting Implementation Retention Study V1. You can use my [created recipe](https://delivery-console.stage.mozaws.net/recipe/882).
- Have a user.js file that contains all the prefs needed to be targeted by the Normandy recipe. You can use my created [user.js](https://drive.google.com/open?id=12j8J7WTMU-ZvHjcUhcutB09Qau_GQ24_).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. In the profile directory copy the user.js file.
3. Restart the browser.
4. After enrolling in the treatmentDomain branch navigate to "about:preferences#privacy" page.
5. Observe which option is set.

[Expected result]:
- The "Standard" or "Strict" option is set.

[Actual result]:
- The "Custom" option is set.
	
[Notes]:
- The issue is not reproducible when enrolling in the Control or treatmentScript branch.
- The issue is not reproducible when enrolling in the treatment branch of the Pref-Flip Experiment: Fingerprinting Protections Retention Study.
- Here is a screen recording with the issue:
![custom option set after enrolling in treatmentDomain branch](https://user-images.githubusercontent.com/19226534/69880307-4d727400-12d2-11ea-8987-d704d7d5dc4d.gif)

**Comment by birdsarah** [comment]
Hi @SoftVision-CosminMuntean. Thanks for your testing.

> The issue is not reproducible when enrolling in the Control or treatmentScript branch.

Only treatmentDomain branch flips the pref so it is expected that we would only be seeing a change in treatmentDomain branch.

> [Expected result] The "Standard" or "Strict" option is set.

This is not my expectation. The study addon is reproducing what I see if I do the process manually: If I open FF69, for example, and manually flip the pref

![Screenshot from 2019-12-02 01-22-00](https://user-images.githubusercontent.com/1796208/69938159-2cf91400-14a2-11ea-8c10-df38b195d68e.png)

Then my about:preferences changes to custom:

![Screenshot from 2019-12-02 01-22-29](https://user-images.githubusercontent.com/1796208/69938177-3b473000-14a2-11ea-9b5d-8cc333c3c8ef.png)

This makes sense to me:
a) The screen should definitely not be Standard as enabling fingerprinting protection is more than standard. 
b) The strict settings are stronger than only enabling fingerprinting protection (e.g. known trackers are blocked in all windows) so again, I would not expect this configuration to be picked.

> The issue is not reproducible when enrolling in the treatment branch of the Pref-Flip Experiment: Fingerprinting Protections Retention Study.

I can't explain that, but that would not be correct behavior for only flipping the fingerprinting protection pref, perhaps that experiment flipped additional preferences. Regardless, the behavior you described is the desired behavior for the treatmentDomain branch. 

---

What is the process for closing issues @SoftVision-CosminMuntean - do you close them after we discuss?

**Comment by SoftVision-CosminMuntean** [comment]
> I can't explain that, but that would not be correct behavior for only flipping the fingerprinting protection pref, perhaps that experiment flipped additional preferences. Regardless, the behavior you described is the desired behavior for the treatmentDomain branch.

This was not reproducible when enrolling in the treatment branch of the Pref-Flip Experiment: Fingerprinting Protections Retention Study because the pref was flipped by Normandy and it was set as "default" pref. 
For this experiment, the add-on flips the pref and set it's set as "modified".

> What is the process for closing issues @SoftVision-CosminMuntean - do you close them after we discuss?

It would be best if you can close the issues if are invalid or are expected.

**Comment by birdsarah** [comment]
> This was not reproducible when enrolling in the treatment branch of the Pref-Flip Experiment: Fingerprinting Protections Retention Study because the pref was flipped by Normandy and it was set as "default" pref.
> For this experiment, the add-on flips the pref and set it's set as "modified".

Thank you for this. I will check with my colleagues and decide whether to close or not.

**Comment by mlopatka** [comment]
@birdsarah @SoftVision-CosminMuntean 
In the spirit of transparency, while still striving to maintain the integrity of the experimental design I posit that this behaviour is expected. In the case that issues with compatibility or user experience arise, we would like users to see that the "custom" Privacy and Security pref has been toggled.

Closing this issue out as expected behaviour.
