### ISSUE TITLE
Unify unenroll codes

### ISSUE THREAD

**Issue by birdsarah** [mozilla/fingerprinting-blocking-methods-study-addon#15]
Reported by @SoftVision-CosminMuntean:

If the “Custom” setting is set and the “Fingerprinters” option is not checked, after enrolling in the treatmentDomain branch, users will be automatically unenrolled with the following reason “0: User has fingerprinting protections enabled.". Based on the TestPlan.md this is correct but the reason is not true since the Fingerprinters option was not checked. 

* Should I log a new issue for this or it will not affect the results of the collected telemetry data?
* Here is a link with a screen recording of the described behavior and a link with the steps.

----

To resolve this, we will reduce unenroll codes to just one. This has the added benefit of not reporting things that could make some inferences about user's existing privacy settings state which is not information we need for this study.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest builds (0.5.0) and is no longer reproducible. The "FPBlock Unenroll" reason is registered.
