### ISSUE TITLE
If user flips fingerprinting pref, treat as other user changes

### ISSUE THREAD

**Issue by birdsarah** [mozilla/fingerprinting-blocking-methods-study-addon#16]
Reported by @SoftVision-CosminMuntean

If the user is enrolled in the “treatmentDomain” branch and manually unchecks the “Fingerprinters” option from the “Custom” setting from “about:preferences#privacy” page,  he is automatically unenrolled from the experiment and the “Standard” setting is set. 
* Since the user makes this change, shouldn't the “Custom” setting remain set?
----
Resolution - also leave as custom if user flipped off.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest builds (0.5.0) and it is no longer reproducible. The "Custom" option remains set after unenrolling in the following cases:
- If the "Fingerprinters" option from the “about:preferences#privacy” page is unchecked.
- If the "privacy.trackingprotection.fingerprinting.enabled" pref is manually changed.
