### ISSUE TITLE
Questions for Fred

### ISSUE THREAD

**Issue by birdsarah** [mozilla/fingerprinting-blocking-methods-study-addon#2]
@motin I have a few random questions for you.

1. I'm currently logging to the Browser console when a request is blocked for debugging. Will this affect performance?
1. I noticed a `hidden` property in the manifest from federated learning, what does that do, do I need it?
1. Have you ever heard of a "behind-the-scenes" request. I'm wondering whether this is standard thing or uBlock terminology. Just curious.

**Comment by motin** [comment]
> I'm currently logging to the Browser console when a request is blocked for debugging. Will this affect performance?

It can definitely affect performance if there is a lot of logging going on.

> I noticed a hidden property in the manifest from federated learning, what does that do, do I need it?

It prevents the add-on from showing up in about:addons once deployed. This is correct since add-on studies should only show up in about:studies.

> Have you ever heard of a "behind-the-scenes" request. I'm wondering whether this is standard thing or uBlock terminology. Just curious.

Haven't heard. If referring to https://github.com/chrisaljoudi/uBlock/wiki/Behind-the-scene-network-requests then yes, seems to be uBlock-specific terminology.

**Comment by birdsarah** [comment]
> Haven't heard.

Great. That was all I needed. Thanks.

>  If referring to https://github.com/chrisaljoudi/uBlock/wiki/Behind-the-scene-network-requests then yes, seems to be uBlock-specific terminology.

I just want to be super clear, I am not working off uBlock LLC / Adblock / chrisaljoudi/uBlock code. See [note from uBlock Origin]( https://github.com/gorhill/uBlock/wiki/uBlock-Origin-is-completely-unrelated-to-the-web-site-ublock.org) or the [wikipedia page](https://en.wikipedia.org/wiki/UBlock_Origin#uBlock) explaining the difference if not familiar. Description of forked and modified code in this repo and the relevant license is available here: https://github.com/mozilla/fingerprinting-blocking-methods-study-addon/blob/master/src/treatment_script/requestBlocking/LICENSE.md

**Comment by birdsarah** [comment]
`hidden` feature added in 9b77e67

**Comment by birdsarah** [comment]
Opened issue to deal with logging. Closing this issue as different items have been dealt with separately. Thanks @motin.

**Comment by birdsarah** [comment]
Just to triple check @motin, I still see my add on in about:addons with `hidden: true` - I'm assuming this property only kicks in when signed?

![Screenshot from 2019-11-20 18-06-27](https://user-images.githubusercontent.com/1796208/69288982-c67e1700-0bc0-11ea-8585-7d3bf642ebd5.png)
