### ISSUE TITLE
prefs remain set after disable/uninstall

### ISSUE THREAD

**Issue by mixedpuppy** [mozilla/fingerprinting-blocking-methods-study-addon#20]
Is the intention to leave prefs set if the addon is removed/disabled?

If not, make use of the static onDisable and onUninstall functions

```
  static onDisable(id) {
    if (id !== context.extension.id) {
      return;
    }
    // For any pref that might have been set by the extension...
    Services.prefs.clearUserPref(...);
  }
  static async onUninstall(id) {
    ....same thing, maybe call a helper function ...
  }
```

Ideally, the extension would track whether it set the pref, and reset it to whatever it was before.

There are ways that the extension could still be uninstalled/disabled that wouldn't trigger this code path (e.g. safe mode), we just have to live with that in experimental APIs.  But the common case gets covered.

**Comment by birdsarah** [comment]
Pref is unset at study end / unenroll. This is covered in TESTPLAN.md and has been tested extensively by QA.
