### ISSUE TITLE
Handle Private Browsing Mode correctly.

### ISSUE THREAD

**Issue by birdsarah** [mozilla/fingerprinting-blocking-methods-study-addon#3]
The script blocking does not appear to be working in Private Browsing Mode.

@motin any ideas why this would be off the top of your head.

**Comment by motin** [comment]
Ordinary/development add-ons are not allowed in Private Browsing by default. To allow, go to about:addons -> The add-on -> Run in Private windows -> Allow.

To disable, set incognito to not_allowed in the manifest. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito

**Comment by birdsarah** [comment]
> To allow, go to about:addons -> The add-on -> Run in Private windows -> Allow.

This worked great and confirmed it working in PBM.

Subsequently realized that default PBM behavior is more strict than script blocking so now want to ensure that addon doesn't run in PBM so as not to potentially reduce user protections during the study. Updated title to reflect.
