### ISSUE TITLE
Clean-up required permissions

### ISSUE THREAD

**Issue by birdsarah** [mozilla/fingerprinting-blocking-methods-study-addon#5]
Currently probably too many after stripping out a lot of code.

**Comment by birdsarah** [comment]
I've removed `privacy` in #6. The remaining permissions for the treatment_script branch are: 
 
```
  "permissions": [
    "normandyAddonStudy",
    "storage",
    "tabs",
    "unlimitedStorage",
    "webNavigation",
    "webRequest",
    "webRequestBlocking",
    "<all_urls>"
  ],
```

And as best as I can tell I need them all.

**Comment by birdsarah** [comment]
> And as best as I can tell I need them all.

This was meant to be framed as a question to @motin :D

**Comment by motin** [comment]
Yes I ran through the list and found every listed permission necessary.

**Comment by birdsarah** [comment]
Thanks!
